app:
  spotlit:
    name: Spotlit
    abbreviation: spotli
    requires:
      - app: cwapps
      - app: cwcore
    icon: citiusdemoicon
    version: 1.1.3
    defaultSite: cnz8
    usernameAbbreviation:
      abbreviation: demo
      username: demo@citius.com
  intro:
    Spotlit:
      title: Spotlit
      text:
        en: Welcome to the Spotlit application.
        fi: Tervetuloa testaamaan Spotlit-applikaatiota
    Disclaimer:
      title:
        en: Disclaimer
        fi: Vastuuvapaus
      text:
        en: This application is used only for internal demonstration purposes for the Blitz-project.
        fi: Tämä Spotlit-applikaatio on demosovellus, jota käytetään vain Blitz-projektin sisäisiin esitystarkoituksiin.
    DemoContent:
      title:
        en: Demo Content
        fi: Demosisältö
      text:
        en: All the content, text and pictures, are just samples.
        fi: Kaikki sisältö, teksti ja kuvat ovat vain näytteitä.
  name: Spotlit
  abbreviation: spotli
  version: 1.1.3
  cScriptVersion: '57'

  # Täällä määritellään applikaation perusväri; käytetään esim. toolbarissa; napeissa jne.
  # Color of the Spotlit logo is 0,174,239 #00AEEF (Deep Sky Blue): https://www.htmlcsscolor.com/hex/00AEEF
  # Shade #008BBF: https://www.htmlcsscolor.com/hex/008BBF
  # Tint #ACE4FA: https://www.htmlcsscolor.com/hex/ACE4FA
  theme:
    color: '#000000'
    android:
      fontFamily: Roboto light
      brandPrimary: '#008BBF'
    ios:
      fontFamily: Avenir-Medium
    style:
      noteluokka:
        color: '#7c7e7f'
      strongluokka:
        color: '#008BBF'
        fontSize: 16px
        fontWeight: bold
        ios:
          fontFamily: Avenir-Heavy
        android:
          fontFamily: Roboto
views:

  login:
    applicationImage: spotlit-login-applicationImage-transparent
    backgroundColor:
      ios: '#ACE4FA'
      android: '#ACE4FA'
    repeatBackgroundImage: true
    fieldBackgroundColor: '#ffffff'
    fieldBorderColor: '#ffffff'
    fieldBorderSize: 1
    fieldTextColor: '#00AEEF'
    fieldTextDisabledColor: '#bbbdbf'
    loginButtonBackgroundColor: '#00AEEF'
    loginButtonDisabledBackgroundColor: '#ffffff'
    loginButtonTextColor: '#00AEEF'
    loginButtonDisabledTextColor: '#bbbdbf'

  leftPanel:

    header:
      backgroundColor: '#008BBF'
      headerBackgroundColor:
        ios: '#ACE4FA'
        android: '#ACE4FA'
      headerImage: spotlit-menu-headerImage-transparent
      headerTextColor: '#008BBF'
      textColor: '#FFFFFF'

    mainmenu:
      type: menu
      title:
        en: Spotlit Menu
        fi: Spotlit valikko
      items:

        welcomeitem:
          title:
            en: Welcome to Spotlit
            fi: Tervetuloa Spotlitiin
          icon: 'simplelineicons:home'
          listeners:
            click: onWelcomeClick

        #privacyitem:
          #title:
            #en: Privacy
            #fi: Yksityisyys
          #icon: 'simplelineicons:lock'
          #listeners:
            #click: onPrivacyClick

        privacymodalitem:
          title:
            en: Privacy
            fi: Yksityisyys
          icon: 'simplelineicons:lock'
          listeners:
            click:
              webpage:
                en: https://www.iubenda.com/privacy-policy/96548006
                fi: https://www.iubenda.com/privacy-policy/96548006

        separatoritem:
          separator: true
          title:
            en: Demo Applications
            fi: Demo-applikaatiot

        KainuuItem:
          title:
            fi: Kainuu
            en: Kainuu
          icon: 'materialcommunityicons:application'
          listeners:
            click: onKainuuClick

        juminkekoitem:
          title:
            fi: Juminkeko
            en: Juminkeko
          icon: 'materialcommunityicons:application'
          listeners:
            click: onJuminkekoClick

        moatbraeitem:
          title:
            fi: Moat Brae
            en: Moat Brae
          icon: 'materialcommunityicons:application'
          listeners:
            click: onMoatBraeClick

        separatoritem2:
          separator: true
          #title:
            #en: Muuta
            #fi: Other stuff

        introduction:
          title:
            fi: App-esittely
            en: App Intro
          icon: 'materialcommunityicons:application'
          listeners:
            click:
              app: intro

  mainPanel:

    map:
      type: map
      title:
        en: Map
        fi: Kartta
      items:
        #table: RUKAST_Property
        csql: "/RUKAST_Property{Name,NameEN,Description,DescriptionEN,Latitude,Longitude,ImageCI}.sort(Name).filter(City='Kajaani')"
      region:
        latitude: 64.22524
        longitude: 27.73745
        latitudeDelta: 0.03
      icon: 'simplelineicons:map'

    partnershipmeeting:
      type: pdf
      title:
        en: Partnership Meeting
        fi: Partnerikokous
      ci:
        en: hh8z3xfnwfkwrmtk
        fi: hh8z3xfnwfkwrmtk
      icon: 'simplelineicons:doc'

    privacy:
      type: page
      title:
        en: Privacy
        fi: Yksityisyys
      ci:
        en: 9e8h
        fi: remn
      icon: 'simplelineicons:lock'
      headerNumbering: false

    schedule:
      type: page
      title:
        en: Schedule
        fi: Aikataulu
      ci:
        en: fxt3
        fi: n96x
      icon: 'simplelineicons:clock'
      headerNumbering: false
      imageTopCI: fpkpfxknp383ttkr
      #imageTopHeight: 150px

    steeringcommitteemeeting:
      type: pdf
      title:
        en: Steering Committee Meeting
        fi: Ohjausryhmän kokous
      ci:
        en: z3h66x39mnkezfrx
        fi: z3h66x39mnkezfrx
      icon: 'simplelineicons:doc'

    welcome:
      type: page
      title:
        en: Welcome to Spotlit
        fi: Tervetuloa Spotlitiin
      ci:
        en: 6WH8
        fi: 3W23
      icon: 'simplelineicons:home'
      headerNumbering: false
      #imageTop: kajaani-winter
      imageTopCI: 9MCZ93RH23N6RCC9

controllers:
  constructor:
    url: welcome
  #onJMBarrieClick:
    #application: barrie
  onJuminkekoClick:
    application: jumink
  onKainuuClick:
    application: spotka
  onMapClick:
    url: map
  onMoatBraeClick:
    application: moatbr
  onPartnershipMeetingClick:
    url: partnershipmeeting
  onPrivacyClick:
    url: privacy
  onScheduleClick:
    url: schedule
  onSteeringCommitteeMeetingClick:
    url: steeringcommitteemeeting
  onWelcomeClick:
    url: welcome
