app:
  spotlit:
    name: Spotlit
    abbreviation: spotli
    requires:
      - app: cwapps
      - app: cwcore
    icon: citiusdemoicon
    version: 1.1.3
    defaultSite: n3e3
    usernameAbbreviation:
      abbreviation: demo
      username: demo@citius.com
  name: Spotlit
  abbreviation: spotli
  version: 1.1.3
  cScriptVersion: '14-alpha'

  # Täällä määritellään applikaation perusväri; käytetään esim. toolbarissa; napeissa jne.
  theme:
    color: '#000000'
    android:
      fontFamily: Roboto light
      brandPrimary: '#0071b8'
    ios:
      fontFamily: Avenir-Medium
    style:
      noteluokka:
        color: '#7c7e7f'
      strongluokka:
        color: '#0071b8'
        fontSize: 16px
        fontWeight: bold
        ios:
          fontFamily: Avenir-Heavy
        android:
          fontFamily: Roboto
views:

  login:
    applicationImage: spotlit-login-applicationImage-transparent
    backgroundColor:
      ios: '#ffffff'
      android: '#e1e7f6'
    repeatBackgroundImage: true
    fieldBackgroundColor: '#ffffff'
    fieldBorderColor: '#0071b8'
    fieldBorderSize: 1
    fieldTextColor: '#0071b8'
    fieldTextDisabledColor: '#bbbdbf'
    loginButtonBackgroundColor: '#0071b8'
    loginButtonDisabledBackgroundColor: '#ffffff'
    loginButtonTextColor: '#ffffff'
    loginButtonDisabledTextColor: '#bbbdbf'

  leftPanel:
    header:
      backgroundColor: '#ffffff'
      headerBackgroundColor:
        ios: '#ffffff'
        android: '#e1e7f6'
      headerImage: spotlit-menu-headerImage-transparent
    mainmenu:
      type: menu
      title:
        en: Spotlit Menu
        fi: Spotlit valikko
      items:
        welcomeitem:
          title:
            en: Welcome
            fi: Tervetuloa
          icon: 'materialcommunityicons:airplane-takeoff'
          listeners:
            click: onWelcomeClick
        separatoritem:
          separator: true
        kalevalaitem:
          title:
            fi: Kalevala
            en: Kalevala
          icon: 'ionicons:ios-plane'
          listeners:
            click: onKalevalaClick
        jmbarrieitem:
          title:
            fi: J. M. Barrie
            en: J. M. Barrie
          icon: 'ionicons:ios-plane'
          listeners:
            click: onJMBarrieClick

  mainPanel:

    welcome:
      type: page
      title:
        en: Welcome
        fi: Tervetuloa
      ci:
        fi: 88rt
        en: 88rt
      icon: ionicons:ios-information-circle-outline
      headerNumbering: false

controllers:
  constructor:
    url: flights
  onKalevalaClick:
    application: kaleva
  onJMBarrieClick:
    application: barrie
  onWelcomeClick:
    url: welcome
