app:
  spotlit:
    name: Spotlit
    abbreviation: spotli
    requires:
      - app: cwapps
      - app: cwcore
    icon: citiusdemoicon
    version: 1.1.3
    defaultSite: cnz8
    usernameAbbreviation:
      abbreviation: demo
      username: demo@citius.com
  name: Spotlit
  abbreviation: spotli
  version: 1.1.3
  cScriptVersion: '27'

  # Täällä määritellään applikaation perusväri; käytetään esim. toolbarissa; napeissa jne.
  theme:
    color: '#000000'
    android:
      fontFamily: Roboto light
      brandPrimary: '#0071b8'
    ios:
      fontFamily: Avenir-Medium
    style:
      noteluokka:
        color: '#7c7e7f'
      strongluokka:
        color: '#0071b8'
        fontSize: 16px
        fontWeight: bold
        ios:
          fontFamily: Avenir-Heavy
        android:
          fontFamily: Roboto
views:

  login:
    applicationImage: spotlit-login-applicationImage-transparent
    backgroundColor:
      ios: '#ffffff'
      android: '#e1e7f6'
    repeatBackgroundImage: true
    fieldBackgroundColor: '#ffffff'
    fieldBorderColor: '#0071b8'
    fieldBorderSize: 1
    fieldTextColor: '#0071b8'
    fieldTextDisabledColor: '#bbbdbf'
    loginButtonBackgroundColor: '#0071b8'
    loginButtonDisabledBackgroundColor: '#ffffff'
    loginButtonTextColor: '#ffffff'
    loginButtonDisabledTextColor: '#bbbdbf'

  leftPanel:

    header:
      backgroundColor: '#ffffff'
      headerBackgroundColor:
        ios: '#ffffff'
        android: '#e1e7f6'
      headerImage: spotlit-menu-headerImage-transparent

    mainmenu:
      type: menu
      title:
        en: Spotlit Menu
        fi: Spotlit valikko
      items:

        welcomeitem:
          title:
            en: Welcome to Kajaani
            fi: Tervetuloa Kajaanin
          icon: 'simplelineicons:home'
          listeners:
            click: onWelcomeClick

        scheduleitem:
          title:
            en: Schedule
            fi: Aikataulu
          icon: 'simplelineicons:clock'
          listeners:
            click: onScheduleClick

        mapitem:
          title:
            en: Map
            fi: Kartta
          icon: 'simplelineicons:map'
          listeners:
            click: onMapClick

        privacyitem:
          title:
            en: Privacy
            fi: Yksityisyys
          icon: 'simplelineicons:lock'
          listeners:
            click: onPrivacyClick

        separatoritem:
          separator: true
          title:
            en: Demo Applications
            fi: Demo-applikaatiot

        juminkekoitem:
          title:
            fi: Juminkeko
            en: Juminkeko
          icon: 'materialcommunityicons:application'
          listeners:
            click: onJuminkekoClick

        moatbraeitem:
          title:
            fi: Moat Brae
            en: Moat Brae
          icon: 'materialcommunityicons:application'
          listeners:
            click: onMoatBraeClick

  mainPanel:

    map:
      type: map
      title:
        en: Map
        fi: Kartta
      #ci:
        #en: hk3p
        #fi: rex8
      icon: 'simplelineicons:map'
      #headerNumbering: false

    privacy:
      type: page
      title:
        en: Privacy
        fi: Yksityisyys
      ci:
        en: 9e8h
        fi: remn
      icon: 'simplelineicons:lock'
      headerNumbering: false

    schedule:
      type: page
      title:
        en: Schedule
        fi: Aikataulu
      ci:
        en: fxt3
        fi: n96x
      icon: 'simplelineicons:clock'
      headerNumbering: false

    welcome:
      type: page
      title:
        en: Welcome
        fi: Tervetuloa
      ci:
        en: thn6
        fi: 88em
      icon: 'simplelineicons:home'
      headerNumbering: false
      imageTop: kajaani-winter
      imageTopCI: w3kkkkzmkch9cw3f

controllers:
  constructor:
    url: welcome
  #onJMBarrieClick:
    #application: barrie
  onJuminkekoClick:
    application: jumink
  onMapClick:
    url: map
  onMoatBraeClick:
    application: moatbr
  onPrivacyClick:
    url: privacy
  onScheduleClick:
    url: schedule
  onWelcomeClick:
    url: welcome
