app:
  wtbf2019:
    name: Wigtown Book Festival 2019
    abbreviation: wtbf19
    requires:
      - app: cwapps
      - app: cwcore
    icon: citiusdemoicon
    version: 1.1.3
    defaultSite: cnz8
    usernameAbbreviation:
      abbreviation: demo
      username: demo@citius.com
  name: Wigtown Book Festival 2019
  abbreviation: wtbf19
  defaultLocale: en
  disableLogin: true
  disableLocale: true
  guestUsername: demo@citius.com
  guestPassword: demo
  version: 1.0.0
  cScriptVersion: '29'

  # Täällä määritellään applikaation perusväri; käytetään esim. toolbarissa; napeissa jne.
  theme:
    color: '#000000'
    android:
      fontFamily: Roboto light
      brandPrimary: '#b54137'
    ios:
      fontFamily: Avenir-Medium
    style:
      noteluokka:
        color: '#7c7e7f'
      strongluokka:
        color: '#0071b8'
        fontSize: 16px
        fontWeight: bold
        ios:
          fontFamily: Avenir-Heavy
        android:
          fontFamily: Roboto
views:

  login:
    applicationImage: wtbf19-login-applicationImage-transparent
    backgroundColor:
      ios: '#d9c6a6'
      android: '#d9c6a6'
    repeatBackgroundImage: true
    fieldBackgroundColor: '#ffffff'
    fieldBorderColor: '#b54137'
    fieldBorderSize: 1
    fieldTextColor: '#b54137'
    fieldTextDisabledColor: '#bbbdbf'
    loginButtonBackgroundColor: '#b54137'
    loginButtonDisabledBackgroundColor: '#ffffff'
    loginButtonTextColor: '#ffffff'
    loginButtonDisabledTextColor: '#bbbdbf'

  leftPanel:

    header:
      #backgroundColor: '#ffffff'
      backgroundColor: '#d9c6a6'
      headerBackgroundColor:
        ios: '#d9c6a6'
        android: '#d9c6a6'
      headerImage: wtbf19-menu-headerImage-transparent
      headerTextColor: '#b54137'
      textColor: '#b54137'

    mainmenu:
      type: menu
      title:
        en: Wigtown Book Festival 2019
        fi: Wigtown Book Festival 2019

      items:

        aboutitem:
          title:
            en: About the Festival
            fi: About the Festival
          icon: 'simplelineicons:info'
          listeners:
            click: onAboutClick

        booktownitem:
          title:
            en: Wigtown Book Town
            fi: Wigtown Book Town
          icon: 'simplelineicons:home'
          listeners:
            click: onBookTownClick

        programmeitem:
          title:
            en: Programme of Events
            fi: Programme of Events
          icon: 'simplelineicons:book-open'
          listeners:
            click: onProgrammeClick

        venuemapitem:
          title:
            en: Venue Map
            fi: Venue Map
          icon: 'simplelineicons:map'
          listeners:
            click:
              webpage:
                en: https://www.wigtownbookfestival.com/visit/festival-venues
                fi: https://www.wigtownbookfestival.com/visit/festival-venues

        howtobookitem:
          title:
            en: How to Book
            fi: How to Book
          icon: 'simplelineicons:basket'
          listeners:
            click: onHowToBookClick

        howtogethereitem:
          title:
            en: How to Get Here
            fi: How to Get Here
          icon: 'simplelineicons:directions'
          listeners:
            click: onHowToGetHereClick

        wheretoeatitem:
          title:
            en: Where to Eat, Drink and Stay
            fi: Where to Eat, Drink and Stay
          icon: 'simplelineicons:cup'
          listeners:
            click:
              webpage:
                en: https://www.wigtownbookfestival.com/visit/eat-drink-stay
                fi: https://www.wigtownbookfestival.com/visit/eat-drink-stay

        whatelsetoseeitem:
          title:
            en: What Else to See
            fi: What Else to See
          icon: 'simplelineicons:picture'
          listeners:
            click: onWhatElseToSeeClick

        findusonsocialmediaitem:
          title:
            en: Find Us on Social Media
            fi: Find Us on Social Media
          icon: 'simplelineicons:social-twitter'
          listeners:
            click: onFindUsOnSocialMediaClick

        separatoritem:
          separator: true
          title:
            en: Introduction
            fi: Esittely

  mainPanel:

    #tabpanel:
      #type: tabs
      #items:

    about:
      type: page
      title:
        en: About the Festival
        fi: About the Festival
      ci:
        en: mfcm
        fi: mfcm
      icon: 'simplelineicons:info'
      headerNumbering: false
      imageTopCI: zfnchx89m9h2nhzp

    booktown:
      type: page
      title:
        en: Wigtown Book Town
        fi: Wigtown Book Town
      ci:
        en: 28pr
        fi: 28pr
      icon: 'simplelineicons:home'
      headerNumbering: false
      imageTopCI: mxhnw9w8nnekn8hc

    findusonsocialmedia:
      type: page
      title:
        en: Find Us on Social Media
        fi: Find Us on Social Media
      ci:
        en: ztfp
        fi: ztfp
      icon: 'simplelineicons:social-twitter'
      headerNumbering: false
      imageTopCI: rtw3c8z2nzxr62wp

    howtobook:
      type: page
      title:
        en: How to Book
        fi: How to Book
      ci:
        en: 2prr
        fi: 2prr
      icon: 'simplelineicons:basket'
      headerNumbering: false
      imageTopCI: zethrthx2whnhxp3

    howtogethere:
      type: page
      title:
        en: How to Get Here
        fi: How to Get Here
      ci:
        en: 368e
        fi: 368e
      icon: 'simplelineicons:directions'
      headerNumbering: false
      imageTopCI: m2fn866rnhnkw6et

    programme:
      type: pdf
      title:
        en: Programme of Events
        fi: Programme of Events
      ci:
        en: 8m2wttt2nznt239w
        fi: 8m2wttt2nznt239w
      icon: 'simplelineicons:book-open'

    whatelsetosee:
      type: page
      title:
        en: What Else to See
        fi: What Else to See
      ci:
        en: pffk
        fi: pffk
      icon: 'simplelineicons:picture'
      headerNumbering: false
      imageTopCI: kcxw6f8we6tkfk8t

controllers:
  constructor:
    url: about
  onAboutClick:
    url: about
  onBookTownClick:
    url: booktown
  onHowToBookClick:
    url: howtobook
  onHowToGetHereClick:
    url: howtogethere
  onFindUsOnSocialMediaClick:
    url: findusonsocialmedia
  onProgrammeClick:
    url: programme
  onWhatElseToSeeClick:
    url: whatelsetosee
