app:
  kainuu:
    name: Spotlit Kainuu
    abbreviation: spotka
    requires:
      - app: cwapps
      - app: cwcore
    icon: citiusdemoicon
    version: 1.1.3
    defaultSite: cnz8
    usernameAbbreviation:
      abbreviation: demo
      username: demo@citius.com
  intro:
    spotlit:
      title: Spotlit Kainuu
      text:
        en: Welcome to the Spotlit Kainuu application.
        fi: Tervetuloa testaamaan Spotlit Kainuu -applikaatiota
    meeting:
      title: Blitz Meeting
      text:
        en: From the application, you will find the basic information about the meeting.
        fi: Applikaatiosta löydät kokouksen perustiedot
  name: Spotlit Kainuu
  abbreviation: spotka
  version: 1.1.3
  cScriptVersion: '43'

  # Täällä määritellään applikaation perusväri; käytetään esim. toolbarissa; napeissa jne.
  theme:
    color: '#000000'
    android:
      fontFamily: Roboto light
      brandPrimary: '#0071b8'
    ios:
      fontFamily: Avenir-Medium
    style:
      noteluokka:
        color: '#7c7e7f'
      strongluokka:
        color: '#0071b8'
        fontSize: 16px
        fontWeight: bold
        ios:
          fontFamily: Avenir-Heavy
        android:
          fontFamily: Roboto
views:

  login:
    applicationImage: spotlit-login-applicationImage-transparent
    backgroundColor:
      ios: '#ffffff'
      android: '#e1e7f6'
    repeatBackgroundImage: true
    fieldBackgroundColor: '#ffffff'
    fieldBorderColor: '#0071b8'
    fieldBorderSize: 1
    fieldTextColor: '#0071b8'
    fieldTextDisabledColor: '#bbbdbf'
    loginButtonBackgroundColor: '#0071b8'
    loginButtonDisabledBackgroundColor: '#ffffff'
    loginButtonTextColor: '#ffffff'
    loginButtonDisabledTextColor: '#bbbdbf'

  leftPanel:

    header:
      backgroundColor: '#ffffff'
      headerBackgroundColor:
        ios: '#ffffff'
        android: '#e1e7f6'
      headerImage: spotlit-menu-headerImage-transparent

    mainmenu:
      type: menu
      title:
        en: Spotlit Menu
        fi: Spotlit valikko
      items:

        welcomeitem:
          title:
            en: Welcome to Kajaani
            fi: Tervetuloa Kajaaniin
          icon: 'simplelineicons:home'
          listeners:
            click: onWelcomeClick

        scheduleitem:
          title:
            en: Schedule
            fi: Aikataulu
          icon: 'simplelineicons:clock'
          listeners:
            click: onScheduleClick

        partnershipmeetingitem:
          title:
            en: Partnership Meeting
            fi: Partnerikokous
          icon: 'simplelineicons:doc'
          listeners:
            click: onPartnershipMeetingClick

        steeringcommitteemeetingitem:
          title:
            en: Steering Committee Meeting
            fi: Ohjausryhmän kokous
          icon: 'simplelineicons:doc'
          listeners:
            click: onSteeringCommitteeMeetingClick

        mapitem:
          title:
            en: Map
            fi: Kartta
          icon: 'simplelineicons:map'
          listeners:
            click: onMapClick

        privacyitem:
          title:
            en: Privacy
            fi: Yksityisyys
          icon: 'simplelineicons:lock'
          listeners:
            click: onPrivacyClick

        #separatoritem:
          #separator: true
          #title:
            #en: Demo Applications
            #fi: Demo-applikaatiot

        #juminkekoitem:
          #title:
            #fi: Juminkeko
            #en: Juminkeko
          #icon: 'materialcommunityicons:application'
          #listeners:
            #click: onJuminkekoClick

        #moatbraeitem:
          #title:
            #fi: Moat Brae
            #en: Moat Brae
          #icon: 'materialcommunityicons:application'
          #listeners:
            #click: onMoatBraeClick

        separatoritem2:
          separator: true
          #title:
            #en: Demo Applications
            #fi: Demo-applikaatiot

        introduction:
          title:
            fi: App-esittely
            en: App Intro
          icon: 'simplelineicons:control-play'
          listeners:
            click:
              app: intro

  mainPanel:

    map:
      type: map
      title:
        en: Map
        fi: Kartta
      items:
        #table: RUKAST_Property
        csql: "/RUKAST_Property{Name,NameEN,Description,DescriptionEN,Latitude,Longitude,ImageCI}.sort(Name).filter(City='Kajaani')"
      region:
        latitude: 64.22524
        longitude: 27.73745
        latitudeDelta: 0.03
      icon: 'simplelineicons:map'

    partnershipmeeting:
      type: pdf
      title:
        en: Partnership Meeting
        fi: Partnerikokous
      ci:
        en: hh8z3xfnwfkwrmtk
        fi: hh8z3xfnwfkwrmtk
      icon: 'simplelineicons:doc'

    privacy:
      type: page
      title:
        en: Privacy
        fi: Yksityisyys
      ci:
        en: 9e8h
        fi: remn
      icon: 'simplelineicons:lock'
      headerNumbering: false

    schedule:
      type: page
      title:
        en: Schedule
        fi: Aikataulu
      ci:
        en: fxt3
        fi: n96x
      icon: 'simplelineicons:clock'
      headerNumbering: false
      imageTopCI: fpkpfxknp383ttkr
      #imageTopHeight: 150px

    steeringcommitteemeeting:
      type: pdf
      title:
        en: Steering Committee Meeting
        fi: Ohjausryhmän kokous
      ci:
        en: z3h66x39mnkezfrx
        fi: z3h66x39mnkezfrx
      icon: 'simplelineicons:doc'

    welcome:
      type: page
      title:
        en: Welcome
        fi: Tervetuloa
      ci:
        en: thn6
        fi: 88em
      icon: 'simplelineicons:home'
      headerNumbering: false
      imageTop: kajaani-winter
      imageTopCI: w3kkkkzmkch9cw3f

controllers:
  constructor:
    url: welcome
  #onJMBarrieClick:
    #application: barrie
  onJuminkekoClick:
    application: jumink
  onMapClick:
    url: map
  onMoatBraeClick:
    application: moatbr
  onPartnershipMeetingClick:
    url: partnershipmeeting
  onPrivacyClick:
    url: privacy
  onScheduleClick:
    url: schedule
  onSteeringCommitteeMeetingClick:
    url: steeringcommitteemeeting
  onWelcomeClick:
    url: welcome
