app:
  moatbrae:
    name: Moat Brae
    abbreviation: moatbr
    requires:
      - app: cwapps
      - app: cwcore
    icon: citiusdemoicon
    version: 1.1.3
    defaultSite: cnz8
    usernameAbbreviation:
      abbreviation: demo
      username: demo@citius.com
  name: Moat Brae
  abbreviation: moatbr
  version: 1.0.0
  cScriptVersion: '5'

  # Täällä määritellään applikaation perusväri; käytetään esim. toolbarissa; napeissa jne.
  theme:
    color: '#000000'
    android:
      fontFamily: Roboto light
      brandPrimary: '#f3ab00'
    ios:
      fontFamily: Avenir-Medium
    style:
      noteluokka:
        color: '#7c7e7f'
      strongluokka:
        color: '#0071b8'
        fontSize: 16px
        fontWeight: bold
        ios:
          fontFamily: Avenir-Heavy
        android:
          fontFamily: Roboto
views:

  login:
    applicationImage: moatbrae-login-applicationImage-transparent
    backgroundColor:
      ios: '#ffffff'
      android: '#e1e7f6'
    repeatBackgroundImage: true
    fieldBackgroundColor: '#ffffff'
    fieldBorderColor: '#0071b8'
    fieldBorderSize: 1
    fieldTextColor: '#0071b8'
    fieldTextDisabledColor: '#bbbdbf'
    loginButtonBackgroundColor: '#0071b8'
    loginButtonDisabledBackgroundColor: '#ffffff'
    loginButtonTextColor: '#ffffff'
    loginButtonDisabledTextColor: '#bbbdbf'

  leftPanel:

    header:
      backgroundColor: '#ffffff'
      headerBackgroundColor:
        ios: '#ffcc00'
        android: '#ffcc00'
      headerImage: moatbrae-menu-headerImage-transparent

    mainmenu:
      type: menu
      title:
        en: Moat Brae Menu
        fi: Moat Brae valikko

      items:
        welcomeitem:
          title:
            en: Welcome to Moat Brae
            fi: Tervetuloa Moat Braeen
          icon: 'simplelineicons:home'
          listeners:
            click: onWelcomeClick

  mainPanel:

    welcome:
      type: page
      title:
        en: Welcome to Moat Brae
        fi: Tervetuloa Moat Braeen
      ci:
        en: ekcw
        fi: 2ppx
      icon: 'simplelineicons:home'
      headerNumbering: false

controllers:
  constructor:
    url: welcome
  onWelcomeClick:
    url: welcome
