---
app:
  kamkhub:
    name: KAMK Hub
    abbreviation: kamkhu
    requires:
      - app: cwapps
      - app: cwcore
    icon: kamkhubicon
    version: 1.1.0
    defaultSite: enmx
    usernameAbbreviation:
      abbreviation: demo
      username: demo@citius.com
  intro:
    spotlit:
      title: KAMK Hub
      text:
        en: Welcome to the KAMK Hub application...
        fi: Tervetuloa KAMK Hub applikaatioon...
    meeting:
      title: Page 1
      text:
        en: KAMK Hub application page 2...
        fi: KAMK Hub applikaatio sivu 2...
    applications:
      title: Page 2
      text:
        en: KAMK Hub application page 3...
        fi: KAMK Hub applikaatio sivu 3...
  name: KAMK Hub
  abbreviation: kamkhu
  version: 1.1.0
  cScriptVersion: '37'

  # Täällä määritellään applikaation perusväri; käytetään esim. toolbarissa; napeissa jne.
  theme:
    color: "#000000"
    android:
      fontFamily: Roboto light
      # RGB: 0, 154, 166
      brandPrimary: "#009aa6"
    ios:
      fontFamily: Avenir-Medium
    style:
      noteluokka:
        color: "#009aa6"
      strongluokka:
        color: "#009aa6"
        fontSize: 16px
        fontWeight: "bold"
        ios:
          fontFamily: Avenir-Heavy
        android:
          fontFamily: Roboto

views:

  login:

    #RGB: R0, G178, B227 (KAMK sininen) #00b2e3
    applicationImage: kamkhub-login-applicationImage-transparent
    backgroundColor:
      ios: '#009aa6'
      android: '#009aa6'
    #repeatBackgroundImage: true
    fieldBackgroundColor: '#ffffff'
    fieldBorderColor: '#ffffff'
    fieldBorderSize: 1
    fieldTextColor: '#00b2e3'
    fieldTextDisabledColor: '#bbbdbf'
    loginButtonBackgroundColor: '#00b2e3'
    loginButtonDisabledBackgroundColor: 'ffffff'
    loginButtonTextColor: '#00b2e3'
    loginButtonDisabledTextColor: '#bbbdbf'

  leftPanel:

    header:
      backgroundColor: '#009aa6'
      headerBackgroundColor:
        ios: '#009aa6'
        android: '#009aa6'
      headerImage: kamkhub-menu-headerImage
      marginTop: 0
      textColor: '#ffffff'
      #headerBackgroundImage:
        #ios: demo-login-backgroundImage-transparent
      #repeatHeaderBackgroundImage: true

    mainmenu:
      type: menu
      title:
        en: KAMK Hub Menu
        fi: KAMK Hub valikko
      items:

        welcomeitem:
          title:
            en: Welcome to KAMK Hub
            fi: Tervetuloa KAMK Hubiin
          icon: 'simplelineicons:home'
          listeners:
            click: onWelcomeClick

        #CoreR&DCompetencesitem:
          #title:
            #en: Core R&D Competences (page)
            #fi: Tutkimus ja kehitys (sivu)
          #icon: 'simplelineicons:home'
          #listeners:
            #click: onCoreR&DCompetencesClick

        #BusinessServicesItem:
          #title:
            #en: Business Services (page)
            #fi: Palvelut työelämälle (sivu)
          #icon: 'simplelineicons:home'
          #listeners:
            #click: onBusinessServicesClick

        CoreR&DCompetencesTileitem:
          title:
            en: Core R&D Competences
            fi: Tutkimus ja kehitys
          icon: 'simplelineicons:home'
          listeners:
            click: onCoreR&DCompetencesTileClick

        BusinessServicesTileItem:
          title:
            en: Business Services
            fi: Palvelut työelämälle
          icon: 'simplelineicons:home'
          listeners:
            click: onBusinessServicesTileClick

        separatoritem:
          separator: true
          title:
            en: Separator Text
            fi: Jaottelun teksti

        introductionitem:
          title:
            fi: App-esittely
            en: App Intro
          icon: 'materialcommunityicons:application'
          listeners:
            click:
              app: intro

  mainPanel:

    BusinessServices:
      type: page
      title:
        en: Business Services
        fi: Palvelut työelämälle
      ci:
        en: ch82
        fi: 2ktm
      icon: 'simplelineicons:home'
      headerNumbering: false
      #imageTop: kajaani-winter
      #imageTopCI: w3kkkkzmkch9cw3f

    BusinessServicesTile:
      type: tile
      title:
        en: Business Services
        fi: Palvelut työelämälle
      # Jos on määritelty tänne, niin käytetään kaikissa items-asetuksissa
      # Väriin on määritelty myös alfa 70 % hex B3
      backgroundColor: '#CAE9EC'
      #textAreaBackgroundColor: '#00b2e3b3'
      #textAreaHeight: 40%
      #textAreaPosition: bottom
      items:

        AIKOPA:
          # LightSeaGreen: https://www.htmlcsscolor.com/hex/1ABC9C
          tileBackgroundColor: '#1ABC9C9E'
          tileBackgroundImage: kamk-aikopa
          title:
            # Mahtuuko kolmelle riville vai pitäisikö muuttaa
            en: AIKOPA - Adult and Continuing Education
            fi: AIKOPA - Koulutus ja valmennus
          listeners:
            click:
              webpage:
                en: https://www.kamk.fi/en/RD-and-Business-Services/AIKOPA
                fi: https://www.kamk.fi/fi/Palvelut-tyoelamalle/Raataloity-koulutus-ja-valmennus

        CEMIS:
          # Emerald: https://www.htmlcsscolor.com/hex/50C878
          tileBackgroundColor: '#50C8789E'
          tileBackgroundImage: kamk-cemis
          title:
            en: CEMIS - Measurement and Information
            fi: Teknologian kaupallistaminen
          listeners:
            click:
              webpage:
                en: https://www.kamk.fi/en/RD-and-Business-Services/Centre-for-Measurements-and-Information-Systems
                fi: https://www.kamk.fi/fi/Palvelut-tyoelamalle/Cemis-Business-Development--palvelut-

        Publications:
          # Deep Lilac: https://www.htmlcsscolor.com/hex/9B59B6
          tileBackgroundColor: '#9B59B69E'
          tileBackgroundImage: kamk-publications
          title:
            en: Publications
            fi: Julkaisut
          listeners:
            click:
              webpage:
                en: https://www.kamk.fi/en/RD-and-Business-Services/Publications
                fi: https://www.kamk.fi/en/RD-and-Business-Services/Publications

        PublicationsDatabase:
          # Cello: https://www.htmlcsscolor.com/hex/34495E
          tileBackgroundColor: '#34495E9E'
          tileBackgroundImage: kamk-publications-database
          title:
            en: Publications Database
            fi: Julkaisutietokanta
          listeners:
            click:
              webpage:
                en: https://www.theseus.fi/handle/10024/1967
                fi: https://www.theseus.fi/handle/10024/1967

        Projects:
          # Summer Sky: https://www.htmlcsscolor.com/hex/3498DB
          tileBackgroundColor: '#3498DB9E'
          tileBackgroundImage: kamk-projects
          title:
            en: Projects
            fi: Projektit
          listeners:
            click:
              webpage:
                en: https://www.kamk.fi/en/RD-and-Business-Services/Projects
                fi: https://www.kamk.fi/fi/Tutkimus-ja-kehitys/Projektit

        AboutKAMK:
          # Sininen (Iris Blue) #00B2E3: https://www.htmlcsscolor.com/hex/00B2E3
          tileBackgroundColor: '#00B2E39E'
          tileBackgroundImage: kamk-about-kamk
          title:
            en: About Kajaani University of Applied Sciences
            fi: Kajaanin ammatti- korkeakoulu
          listeners:
            click:
              webpage:
                en: https://www.kamk.fi/en/KAMK
                fi: https://www.kamk.fi/fi/KAMK

        Contact:
          # Oranssi (Tahiti Gold) #EE7623: https://www.htmlcsscolor.com/hex/EE7623
          tileBackgroundColor: '#EE76239E'
          tileBackgroundImage: kamk-contact
          title:
            en: Contact
            fi: Yhteystiedot
          listeners:
            click:
              webpage:
                en: https://www.kamk.fi/en/KAMK/Contact-Information
                fi: https://www.kamk.fi/fi/KAMK/Yhteystiedot

        CampusMap:
          # Petrooli (Bondi Blue) #009AA6: https://www.htmlcsscolor.com/hex/009AA6
          tileBackgroundColor: '#009AA69E'
          tileBackgroundImage: kamk-campus-map
          title:
            en: Campus Map
            fi: Kampuskartta
          listeners:
            click:
              pdf:
                ci:
                  en: mfkrchrw2xzp8tf3
                  fi: khf6kehhrnmne8n3

    CoreR&DCompetences:
      type: page
      title:
        en: Core R&D Competences otsikko
        fi: Tutkimus ja kehitys otsikko
      ci:
        en: nmwt
        fi: c6mf
      icon: 'simplelineicons:home'
      headerNumbering: false
      #imageTop: kajaani-winter
      #imageTopCI: w3kkkkzmkch9cw3f

    CoreR&DCompetencesTile:
      type: tile
      title:
        en: Core R&D Competences
        fi: Tutkimus ja kehitys
      backgroundColor: '#CAE9EC'
      #textAreaBackgroundColor: '#00b2e3b3'
      #textAreaHeight: 40%
      #textAreaPosition: bottom
      items:

        TourismAndSports:
          # Cello: https://www.htmlcsscolor.com/hex/34495E
          tileBackgroundColor: '#34495E9E'
          tileBackgroundImage: kamk-tourism-and-sports
          title:
            en: Tourism and Sports
            fi: Matkailun ja liikunnan osaaminen
          listeners:
            click:
              webpage:
                en: https://www.kamk.fi/en/RD-and-Business-Services/Core-Ramp;D-Competences/Tourism-and-sports-competence
                fi: https://www.kamk.fi/fi/Tutkimus-ja-kehitys/Matkailun-ja-liikunnan-osaaminen

        WellbeingHealthAndGreenCare:
          # Violetti (Palatinate Purple) #612166: https://www.htmlcsscolor.com/hex/612166
          tileBackgroundColor: '#6121669E'
          tileBackgroundImage: kamk-wellbeing-health-and-green-care
          title:
            en: Wellbeing, Health and Green Care
            fi: Hyvinvointi-, terveysosaaminen ja Green Care
          listeners:
            click:
              webpage:
                en: https://www.kamk.fi/en/RD-and-Business-Services/Core-Ramp;D-Competences/Wellbeing-and-health-competence--Green-Care
                fi: https://www.kamk.fi/fi/Tutkimus-ja-kehitys/Hyvinvointi---ja-terveysosaaminen

        SeriousGameApplications:
          # Petrooli (Bondi Blue) #009AA6: https://www.htmlcsscolor.com/hex/009AA6
          tileBackgroundColor: '#009AA69E'
          tileBackgroundImage: kamk-serious-game-applications
          title:
            en: Serious Game Applications
            fi: Pelien hyötysovellukset (VR/AR)
          listeners:
            click:
              webpage:
                en: https://www.kamk.fi/en/RD-and-Business-Services/Core-Ramp;D-Competences/Serious-game-applications-(VRAR)
                fi: https://www.kamk.fi/fi/Tutkimus-ja-kehitys/Pelien-hyotysovellukset

        DataCentre:
          #LightSeaGreen: https://www.htmlcsscolor.com/hex/1ABC9C
          tileBackgroundColor: '#1ABC9C9E'
          #tileBackgroundColor: '#0000004d'
          #textAreaBackgroundColor: '#0000004d'
          #textAreaHeight: 40%
          #textAreaPosition: bottom
          tileBackgroundImage: kamk-data-centre
          title:
            # Mahtuuko kolmelle riville vai pitäisikö muuttaa
            en: Data Centre
            fi: Datakeskus- osaaminen
          listeners:
            click:
              webpage:
                en: https://www.kamk.fi/en/RD-and-Business-Services/Core-Ramp;D-Competences/Data-Centre-competence-
                fi: https://www.kamk.fi/fi/Tutkimus-ja-kehitys/Datakeskusosaaminen

        IndustrialMaterialApplications:
          # Summer Sky: https://www.htmlcsscolor.com/hex/3498DB
          tileBackgroundColor: '#3498DB9E'
          #tileBackgroundColor: '#0000004d'
          tileBackgroundImage: kamk-industrial-material-applications
          title:
            en: Industrial Material Applications
            fi: Teollisten materiaalien soveltaminen
          listeners:
            click:
              webpage:
                en: https://www.kamk.fi/en/RD-and-Business-Services/Core-Ramp;D-Competences/Industrial-materials-applications
                fi: https://www.kamk.fi/fi/Tutkimus-ja-kehitys/Teollisten-materiaalien-soveltaminen

        MeasurementInformationAndRobotics:
          # Deep Lilac: https://www.htmlcsscolor.com/hex/9B59B6
          tileBackgroundColor: '#9B59B69E'
          tileBackgroundImage: kamk-cemis
          title:
            en: Measurement, Information And Robotics
            fi: Mittaus- ja tietojärjestelmät sekä robotiikka
          listeners:
            click:
              webpage:
                en: https://www.kamk.fi/en/RD-and-Business-Services/Core-Ramp;D-Competences/Measurement-and-information-systems--Robotics
                fi: https://www.kamk.fi/fi/Tutkimus-ja-kehitys/Mittaus--ja-tietojarjestelmat

        ProjectPreparationExpertise:
          # Sininen (Iris Blue) #00B2E3: https://www.htmlcsscolor.com/hex/00B2E3
          tileBackgroundColor: '#00B2E39E'
          tileBackgroundImage: kamk-project-preparation-expertise
          title:
            en: Project Preparation Expertise
            fi: Asiantuntijuutta projektien valmisteluun
          listeners:
            click:
              webpage:
                en: https://www.kamk.fi/en/RD-and-Business-Services/Core-Ramp;D-Competences/Project-preparation-expertise
                fi: https://www.kamk.fi/fi/Tutkimus-ja-kehitys/Asiantuntijuutta-projektien-valmisteluun

        EnterpriseAndBusinessDevelopment:
          # Emerald: https://www.htmlcsscolor.com/hex/50C878
          tileBackgroundColor: '#50C8789E'
          #tileBackgroundColor: '#0000004d'
          tileBackgroundImage: kamk-enterprice-and-business-development
          title:
            en: Enterprise and Business Development
            fi: Yrittäjyys ja liiketoiminnan kehittäminen
          listeners:
            click:
              webpage:
                en: https://www.kamk.fi/en/RD-and-Business-Services/Core-Ramp;D-Competences/Enterprise-and-business-development
                fi: https://www.kamk.fi/fi/Tutkimus-ja-kehitys/Yrittajyys-ja-liiketoiminnan-kehittaminen

    welcome:
      type: page
      title:
        en: Welcome to KAMK Hub
        fi: Tervetuloa KAMK Hubiin!
      ci:
        en: p63z
        fi: z9n3
      icon: 'simplelineicons:home'
      headerNumbering: false
      #imageTop: kamk-rd-and-business-services
      #imageTopCI: wtr9wxnmfmrrh36p
      imageTopCI: WTR9WXNMFMRRH36P

controllers:
  constructor:
    url: welcome
  onBusinessServicesClick:
    url: BusinessServices
  onBusinessServicesTileClick:
    url: BusinessServicesTile
  onCoreR&DCompetencesClick:
    url: CoreR&DCompetences
  onCoreR&DCompetencesTileClick:
    url: CoreR&DCompetencesTile
  onWelcomeClick:
    url: welcome

# KAMK värit:
# Petrooli (Bondi Blue) #009AA6: https://www.htmlcsscolor.com/hex/009AA6
# Pinkki (Razzmatazz) #D6006D: https://www.htmlcsscolor.com/hex/D6006D
# Violetti (Palatinate Purple) #612166: https://www.htmlcsscolor.com/hex/612166
# Oranssi (Tahiti Gold) #EE7623: https://www.htmlcsscolor.com/hex/EE7623
# Vihreä (Citrus) #80BC00: https://www.htmlcsscolor.com/hex/80BC00
# Sininen (Iris Blue) #00B2E3: https://www.htmlcsscolor.com/hex/00B2E3
# 
# Muut värit:
# LightSeaGreen #1ABC9C: https://www.htmlcsscolor.com/hex/1ABC9C
# Emerald #50C878: https://www.htmlcsscolor.com/hex/50C878
# Summer Sky #3498DB: https://www.htmlcsscolor.com/hex/3498DB
# Deep Lilac #9B59B6: https://www.htmlcsscolor.com/hex/9B59B6
# Cello #34495E: https://www.htmlcsscolor.com/hex/34495E
