app:
  kamkhub:
    name: KAMK Hub
    abbreviation: kamkhu
    requires:
      - app: cwapps
      - app: cwcore
    icon: kamkhubicon
    version: 1.1.0
    defaultSite: enmx
    usernameAbbreviation:
      abbreviation: demo
      username: demo@citius.com
  intro:
    spotlit:
      title: KAMK Hub
      text:
        en: Welcome to the KAMK Hub application...
        fi: Tervetuloa KAMK Hub applikaatioon...
    meeting:
      title: Page 1
      text:
        en: KAMK Hub application page 2...
        fi: KAMK Hub applikaatio sivu 2...
    applications:
      title: Page 2
      text:
        en: KAMK Hub application page 3...
        fi: KAMK Hub applikaatio sivu 3...
  name: KAMK Hub
  abbreviation: kamkhu
  version: 1.1.0
  cScriptVersion: '16'

  # Täällä määritellään applikaation perusväri; käytetään esim. toolbarissa; napeissa jne.
  theme:
    color: "#000000"
    android:
      fontFamily: Roboto light
      # RGB: 0, 154, 166
      brandPrimary: "#009aa6"
    ios:
      fontFamily: Avenir-Medium
    style:
      noteluokka:
        color: "#009aa6"
      strongluokka:
        color: "#009aa6"
        fontSize: 16px
        fontWeight: "bold"
        ios:
          fontFamily: Avenir-Heavy
        android:
          fontFamily: Roboto

views:

  login:

    #RGB: R0, G178, B227 (KAMK sininen) #00b2e3
    applicationImage: kamkhub-login-applicationImage-transparent
    backgroundColor:
      ios: '#009aa6'
      android: '#009aa6'
    #repeatBackgroundImage: true
    fieldBackgroundColor: '#ffffff'
    fieldBorderColor: '#ffffff'
    fieldBorderSize: 1
    fieldTextColor: '#ffffff'
    #fieldTextColor: '#00b2e3'
    fieldTextDisabledColor: '#bbbdbf'
    loginButtonBackgroundColor: '#00b2e3'
    loginButtonDisabledBackgroundColor: 'ffffff'
    loginButtonTextColor: '#00b2e3'
    loginButtonDisabledTextColor: '#bbbdbf'

  leftPanel:

    header:
      backgroundColor: '#009aa6'
      headerBackgroundColor:
        ios: '#009aa6'
        android: '#009aa6'
      headerImage: kamkhub-menu-headerImage
      marginTop: 0
      textColor: '#ffffff'
      #headerBackgroundImage:
        #ios: demo-login-backgroundImage-transparent
      #repeatHeaderBackgroundImage: true

    mainmenu:
      type: menu
      title:
        en: KAMK Hub Menu
        fi: KAMK Hub valikko
      items:

        welcomeitem:
          title:
            en: Welcome to KAMK Hub
            fi: Tervetuloa KAMK Hubiin
          icon: 'simplelineicons:home'
          listeners:
            click: onWelcomeClick

        CoreR&DCompetencesitem:
          title:
            en: 'Core R&D Competences'
            fi: 'Tutkimus ja kehitys'
          icon: 'simplelineicons:home'
          listeners:
            click: onCoreR&DCompetencesClick

        businessservicesitem:
          title:
            en: Business Services
            fi: Työelämän palvelut
          icon: 'simplelineicons:home'
          listeners:
            click: onBusinessServicesClick

        separatoritem:
          separator: true
          title:
            en: Separator Text
            fi: Jaottelun teksti

        introductionitem:
          title:
            fi: App-esittely
            en: App Intro
          icon: 'materialcommunityicons:application'
          listeners:
            click:
              app: intro

  mainPanel:

    businessservices:
      type: tile

    welcome:
      type: page
      title:
        en: Welcome
        fi: Tervetuloa
      ci:
        en: p63z
        fi: z9n3
      icon: 'simplelineicons:home'
      headerNumbering: false
      #imageTop: kajaani-winter
      #imageTopCI: w3kkkkzmkch9cw3f

    CoreR&DCompetences:
      type: page
      title:
        en: 'Core R&D Competences otsikko'
        fi: 'Tutkimus ja kehitys otsikko'
      ci:
        en: nmwt
        fi: c6mf
      icon: 'simplelineicons:home'
      headerNumbering: false
      #imageTop: kajaani-winter
      #imageTopCI: w3kkkkzmkch9cw3f

controllers:
  constructor:
    url: welcome
  onBusinessServicesClick:
    url: businessservices
  onCoreR&DCompetencesClick:
    url: CoreR&DCompetences
  onWelcomeClick:
    url: welcome
