app:
  kamkhub:
    name: KAMK Hub
    abbreviation: kamkhu
    requires:
      - app: cwapps
      - app: cwcore
    icon: kamkhubicon
    version: 1.1.0
    defaultSite: enmx
    usernameAbbreviation:
      abbreviation: demo
      username: demo@citius.com
  intro:
    spotlit:
      title: KAMK Hub
      text:
        en: Welcome to the KAMK Hub application...
        fi: Tervetuloa KAMK Hub applikaatioon...
    meeting:
      title: Page 1
      text:
        en: KAMK Hub application page 2...
        fi: KAMK Hub applikaatio sivu 2...
    applications:
      title: Page 2
      text:
        en: KAMK Hub application page 3...
        fi: KAMK Hub applikaatio sivu 3...
  name: KAMK Hub
  abbreviation: kamkhu
  version: 1.1.0
  cScriptVersion: '18'

  # Täällä määritellään applikaation perusväri; käytetään esim. toolbarissa; napeissa jne.
  theme:
    color: "#000000"
    android:
      fontFamily: Roboto light
      # RGB: 0, 154, 166
      brandPrimary: "#009aa6"
    ios:
      fontFamily: Avenir-Medium
    style:
      noteluokka:
        color: "#009aa6"
      strongluokka:
        color: "#009aa6"
        fontSize: 16px
        fontWeight: "bold"
        ios:
          fontFamily: Avenir-Heavy
        android:
          fontFamily: Roboto

views:

  login:

    #RGB: R0, G178, B227 (KAMK sininen) #00b2e3
    applicationImage: kamkhub-login-applicationImage-transparent
    backgroundColor:
      ios: '#009aa6'
      android: '#009aa6'
    #repeatBackgroundImage: true
    fieldBackgroundColor: '#ffffff'
    fieldBorderColor: '#ffffff'
    fieldBorderSize: 1
    fieldTextColor: '#ffffff'
    #fieldTextColor: '#00b2e3'
    fieldTextDisabledColor: '#bbbdbf'
    loginButtonBackgroundColor: '#00b2e3'
    loginButtonDisabledBackgroundColor: 'ffffff'
    loginButtonTextColor: '#00b2e3'
    loginButtonDisabledTextColor: '#bbbdbf'

  leftPanel:

    header:
      backgroundColor: '#009aa6'
      headerBackgroundColor:
        ios: '#009aa6'
        android: '#009aa6'
      headerImage: kamkhub-menu-headerImage
      marginTop: 0
      textColor: '#ffffff'
      #headerBackgroundImage:
        #ios: demo-login-backgroundImage-transparent
      #repeatHeaderBackgroundImage: true

    mainmenu:
      type: menu
      title:
        en: KAMK Hub Menu
        fi: KAMK Hub valikko
      items:

        welcomeitem:
          title:
            en: Welcome to KAMK Hub
            fi: Tervetuloa KAMK Hubiin
          icon: 'simplelineicons:home'
          listeners:
            click: onWelcomeClick

        CoreR&DCompetencesitem:
          title:
            en: Core R&D Competences (page)
            fi: Tutkimus ja kehitys (sivu)
          icon: 'simplelineicons:home'
          listeners:
            click: onCoreR&DCompetencesClick

        BusinessServicesItem:
          title:
            en: Business Services (page)
            fi: Palvelut työelämälle (sivu)
          icon: 'simplelineicons:home'
          listeners:
            click: onBusinessServicesClick

        CoreR&DCompetencesTileitem:
          title:
            en: Core R&D Competences (tile)
            fi: Tutkimus ja kehitys (tile)
          icon: 'simplelineicons:home'
          listeners:
            click: onCoreR&DCompetencesTileClick

        BusinessServicesTileItem:
          title:
            en: Business Services (tile)
            fi: Palvelut työelämälle (tile)
          icon: 'simplelineicons:home'
          listeners:
            click: onBusinessServicesTileClick

        separatoritem:
          separator: true
          title:
            en: Separator Text
            fi: Jaottelun teksti

        introductionitem:
          title:
            fi: App-esittely
            en: App Intro
          icon: 'materialcommunityicons:application'
          listeners:
            click:
              app: intro

  mainPanel:

    BusinessServices:
      type: page
      title:
        en: Business Services
        fi: Palvelut työelämälle
      ci:
        en: ch82
        fi: 2ktm
      icon: 'simplelineicons:home'
      headerNumbering: false
      #imageTop: kajaani-winter
      #imageTopCI: w3kkkkzmkch9cw3f

    BusinessServicesTile:
      type: tile
      title:
        en: Business Services
        fi: Palvelut työelämälle
      # Jos on määritelty tänne, niin käytetään kaikissa items-asetuksissa
      # Väriin on määritelty myös alfa 70 % hex B3
      textAreaBackgroundColor: '#00b2e3b3'
      textAreaHeight: 40%
      textAreaPosition: bottom
      items:

        AIKOPA:
          #LightSeaGreen: https://www.htmlcsscolor.com/hex/1ABC9C
          tileBackgroundColor: '#1ABC9C'
          title:
            # Mahtuuko kolmelle riville vai pitäisikö muuttaa
            en: AIKOPA - Adult and Continuing Education Services
            fi: AIKOPA - Räätälöity koulutus ja valmennus
          listeners:
            click:
              webpage:
                en: https://www.kamk.fi/en/RD-and-Business-Services/AIKOPA
                fi: https://www.kamk.fi/fi/Palvelut-tyoelamalle/Raataloity-koulutus-ja-valmennus

        CEMIS:
          # Emerald: https://www.htmlcsscolor.com/hex/50C878
          tileBackgroundColor: '#50C878'
          title:
            en: CEMIS - the Centre for Measurements and Information Systems
            fi: CEMIS - the Centre for Measurements and Information Systems
          listeners:
            click:
              webpage:
                en: https://www.kamk.fi/en/RD-and-Business-Services/Centre-for-Measurements-and-Information-Systems
                fi: https://www.kamk.fi/fi/Palvelut-tyoelamalle/Cemis-Business-Development--palvelut-

        Projects:
          # Summer Sky: https://www.htmlcsscolor.com/hex/3498DB
          tileBackgroundColor: '#3498DB'
          title:
            en: Projects
            fi: CEMIS - the Centre for Measurements and Information Systems
          listeners:
            click:
              webpage:
                en: https://www.kamk.fi/en/RD-and-Business-Services/Projects
                fi: https://www.kamk.fi/fi/Tutkimus-ja-kehitys/Projektit

        Publications:
          # Deep Lilac: https://www.htmlcsscolor.com/hex/9B59B6
          tileBackgroundColor: '#9B59B6'
          title:
            en: Publications
            fi: Julkaisut
          listeners:
            click:
              webpage:
                en: https://www.kamk.fi/en/RD-and-Business-Services/Publications
                fi: https://www.kamk.fi/en/RD-and-Business-Services/Publications

        PublicationsDatabase:
          # Cello: https://www.htmlcsscolor.com/hex/34495E
          tileBackgroundColor: '#34495E'
          title:
            en: Publications Database
            fi: Julkaisutietokanta
          listeners:
            click:
              webpage:
                en: https://www.theseus.fi/handle/10024/1967
                fi: https://www.theseus.fi/handle/10024/1967

    CoreR&DCompetences:
      type: page
      title:
        en: Core R&D Competences otsikko
        fi: Tutkimus ja kehitys otsikko
      ci:
        en: nmwt
        fi: c6mf
      icon: 'simplelineicons:home'
      headerNumbering: false
      #imageTop: kajaani-winter
      #imageTopCI: w3kkkkzmkch9cw3f

    CoreR&DCompetencesTile:
      type: tile
      title:
        en: Core R&D Competences
        fi: Tutkimus ja kehitys

    welcome:
      type: page
      title:
        en: Welcome
        fi: Tervetuloa
      ci:
        en: p63z
        fi: z9n3
      icon: 'simplelineicons:home'
      headerNumbering: false
      #imageTop: kajaani-winter
      #imageTopCI: w3kkkkzmkch9cw3f

controllers:
  constructor:
    url: welcome
  onBusinessServicesClick:
    url: BusinessServices
  onBusinessServicesTileClick:
    url: BusinessServicesTile
  onCoreR&DCompetencesClick:
    url: CoreR&DCompetences
  onCoreR&DCompetencesTileClick:
    url: CoreR&DCompetencesTile
  onWelcomeClick:
    url: welcome
