app:
  kamkhub:
    name: KAMK Hub
    abbreviation: kamkhu
    requires:
      - app: cwapps
      - app: cwcore
    icon: kamkhubicon
    version: 1.1.0
    defaultSite: enmx
    usernameAbbreviation:
      abbreviation: demo
      username: demo@citius.com
  intro:
    spotlit:
      title: KAMK Hub
      text:
        en: Welcome to the KAMK Hub application...
        fi: Tervetuloa KAMK Hub applikaatioon...
    meeting:
      title: Page 1
      text:
        en: KAMK Hub application page 2...
        fi: KAMK Hub applikaatio sivu 2...
    applications:
      title: Page 2
      text:
        en: KAMK Hub application page 3...
        fi: KAMK Hub applikaatio sivu 3...
  name: KAMK Hub
  abbreviation: kamkhu
  version: 1.1.0
  cScriptVersion: '8'

  # Täällä määritellään applikaation perusväri; käytetään esim. toolbarissa; napeissa jne.
  theme:
    color: "#000000"
    android:
      fontFamily: Roboto light
      # RGB: 0, 154, 166
      brandPrimary: "#009aa6"
    ios:
      fontFamily: Avenir-Medium
    style:
      noteluokka:
        color: "#009aa6"
      strongluokka:
        color: "#009aa6"
        fontSize: 16px
        fontWeight: "bold"
        ios:
          fontFamily: Avenir-Heavy
        android:
          fontFamily: Roboto

views:

  login:
    applicationImage: kamkhub-login-applicationImage-transparent
    backgroundColor:
      ios: '#009aa6'
      android: '#009aa6'
    #repeatBackgroundImage: true
    fieldBackgroundColor: '#ffffff'
    fieldBorderColor: '#612166'
    fieldBorderSize: 1
    fieldTextColor: '#612166'
    fieldTextDisabledColor: '#bbbdbf'
    #RBG: R97, G33, B102 (KAMK violetti)
    loginButtonBackgroundColor: '#612166'
    loginButtonDisabledBackgroundColor: 'ffffff'
    loginButtonTextColor: '#612166'
    loginButtonDisabledTextColor: '#bbbdbf'

  leftPanel:

    header:
      backgroundColor: '#009aa6'
      headerBackgroundColor:
        ios: '#009aa6'
        android: '#009aa6'
      headerImage: kamkhub-menu-headerImage
      marginTop: 0
      textColor: '#ffffff'
      #headerBackgroundImage:
        #ios: demo-login-backgroundImage-transparent
      #repeatHeaderBackgroundImage: true

    mainmenu:
      type: menu
      title:
        en: KAMK Hub Menu
        fi: KAMK Hub valikko
      items:

        welcomeitem:
          title:
            en: Welcome to KAMK Hub
            fi: Tervetuloa KAMK Hubiin
          icon: 'simplelineicons:home'
          listeners:
            click: onWelcomeClick

        CoreR&DCompetences:
          title:
            en: Core R&D Competences
            fi: Tutkimus ja kehitys
          icon: 'simplelineicons:home'
          listeners:
            click: onCoreR&DCompetencesClick

        tourismandsportsitem:
          title:
            en: Tourism and Sports
            fi: Matkailu-ja liikunta-alan
          icon: 'simplelineicons:home'
          listeners:
            click: onTourismAndSportsClick

        separatoritem:
          separator: true
          title:
            en: Separator Text
            fi: Jaottelun teksti

        introduction:
          title:
            fi: App-esittely
            en: App Intro
          icon: 'materialcommunityicons:application'
          listeners:
            click:
              app: intro

  mainPanel:

    welcome:
      type: page
      title:
        en: Welcome
        fi: Tervetuloa
      ci:
        en: p63z
        fi: z9n3
      icon: 'simplelineicons:home'
      headerNumbering: false
      #imageTop: kajaani-winter
      #imageTopCI: w3kkkkzmkch9cw3f

    CoreR&DCompetences:
      type: page
      title:
        en: Core R&D Competences
        fi: Tutkimus ja kehitys
      ci:
        en: nmwt
        fi: c6mf
      icon: 'simplelineicons:home'
      headerNumbering: false
      #imageTop: kajaani-winter
      #imageTopCI: w3kkkkzmkch9cw3f

controllers:
  constructor:
    url: welcome
  onCoreR&DCompetencesClick:
    url: CoreR&DCompetences
  onWelcomeClick:
    url: welcome
