app:
  cmobde:
    name: CitiusMobile Development
    abbreviation: cmobde
    requires:
      - app: cwapps
      - app: cwcore
    icon: citiusmobiledevicon
    version: 1.0.0
    defaultSite: n3e3
    #usernameAbbreviation:
      #abbreviation: demo
      #username: demo@citius.com
  intro:
    welcome:
      title: CitiusMobile Development
      text:
        en: Welcome to the CitiusMobile Development application.
        fi: Tervetuloa testaamaan CitiusMobile Development applikaatiota
    secondpage:
      title: The second page
      text:
        en: This is the seocnd page for the intro.
        fi: Tämä on intron toinen sivu.
  name: CitiusMobile Development
  abbreviation: cmobde
  version: 1.1.3
  cScriptVersion: '5'

  # Täällä määritellään applikaation perusväri; käytetään esim. toolbarissa; napeissa jne.
  theme:
    color: '#000000'
    android:
      fontFamily: Roboto light
      brandPrimary: '#0071b8'
    ios:
      fontFamily: Avenir-Medium
    style:
      noteluokka:
        color: '#7c7e7f'
      strongluokka:
        color: '#0071b8'
        fontSize: 16px
        fontWeight: bold
        ios:
          fontFamily: Avenir-Heavy
        android:
          fontFamily: Roboto
views:

  login:
    applicationImage: spotlit-login-applicationImage-transparent
    backgroundColor:
      ios: '#ffffff'
      android: '#e1e7f6'
    repeatBackgroundImage: true
    fieldBackgroundColor: '#ffffff'
    fieldBorderColor: '#0071b8'
    fieldBorderSize: 1
    fieldTextColor: '#0071b8'
    fieldTextDisabledColor: '#bbbdbf'
    loginButtonBackgroundColor: '#0071b8'
    loginButtonDisabledBackgroundColor: '#ffffff'
    loginButtonTextColor: '#ffffff'
    loginButtonDisabledTextColor: '#bbbdbf'

  leftPanel:

    header:
      backgroundColor: '#ffffff'
      headerBackgroundColor:
        ios: '#ffffff'
        android: '#e1e7f6'
      headerImage: spotlit-menu-headerImage-transparent

    mainmenu:
      type: menu
      title:
        en: Spotlit Menu
        fi: Spotlit valikko
      items:

        welcomeitem:
          title:
            en: Welcome to CitiusMobile Development
            fi: Tervetuloa CitiusMobile Development
          icon: 'simplelineicons:home'
          listeners:
            click: onWelcomeClick

        separatoritem:
          separator: true
          title:
            en: Demo Applications
            fi: Demo-applikaatiot

        kunnossapitoitem:
          title:
            fi: Kunnossapito
            en: Kunnossapito
          icon: 'materialcommunityicons:application'
          listeners:
            click: onKunnossapitoClick

        juminkekoitem:
          title:
            fi: Juminkeko
            en: Juminkeko
          icon: 'materialcommunityicons:application'
          listeners:
            click: onJuminkekoClick

        moatbraeitem:
          title:
            fi: Moat Brae
            en: Moat Brae
          icon: 'materialcommunityicons:application'
          listeners:
            click: onMoatBraeClick

        separatoritem2:
          separator: true
          title:
            en: Demo Applications
            fi: Demo-applikaatiot

        privacymodalitem:
          title:
            en: Privacy
            fi: Yksityisyys
          icon: 'simplelineicons:lock'
          listeners:
            click:
              webpage:
                en: https://www.iubenda.com/privacy-policy/36150818
                fi: https://www.iubenda.com/privacy-policy/36150818

        introduction:
          title:
            fi: App-esittely
            en: App Intro
          icon: 'materialcommunityicons:application'
          listeners:
            click:
              app: intro

  mainPanel:

    welcome:
      type: page
      title:
        en: Welcome
        fi: Tervetuloa
      ci:
        en: 2zfm
        fi: 3npt
      icon: 'simplelineicons:home'
      headerNumbering: false
      #imageTop: kajaani-winter
      #imageTopCI: w3kkkkzmkch9cw3f

controllers:
  constructor:
    url: welcome
  onJuminkekoClick:
    application: jumink
  onKunnossapitoClick:
    application: cwcmms
  onMoatBraeClick:
    application: moatbr
  onWelcomeClick:
    url: welcome
