app:
  juminkeko:
    name: Juminkeko
    abbreviation: jumink
    requires:
      - app: cwapps
      - app: cwcore
    icon: citiusdemoicon
    version: 1.1.3
    defaultSite: n3e3
    usernameAbbreviation:
      abbreviation: demo
      username: demo@citius.com
  name: Juminkeko
  abbreviation: jumink
  version: 1.0.0
  cScriptVersion: '2-alpha'

  # Täällä määritellään applikaation perusväri; käytetään esim. toolbarissa; napeissa jne.
  theme:
    color: '#000000'
    android:
      fontFamily: Roboto light
      brandPrimary: '#a14815'
    ios:
      fontFamily: Avenir-Medium
    style:
      noteluokka:
        color: '#7c7e7f'
      strongluokka:
        color: '#0071b8'
        fontSize: 16px
        fontWeight: bold
        ios:
          fontFamily: Avenir-Heavy
        android:
          fontFamily: Roboto
views:

  login:
    applicationImage: juminkeko-login-applicationImage-transparent
    backgroundColor:
      ios: '#ffffff'
      android: '#e1e7f6'
    repeatBackgroundImage: true
    fieldBackgroundColor: '#ffffff'
    fieldBorderColor: '#0071b8'
    fieldBorderSize: 1
    fieldTextColor: '#0071b8'
    fieldTextDisabledColor: '#bbbdbf'
    loginButtonBackgroundColor: '#0071b8'
    loginButtonDisabledBackgroundColor: '#ffffff'
    loginButtonTextColor: '#ffffff'
    loginButtonDisabledTextColor: '#bbbdbf'

  leftPanel:

    header:
      backgroundColor: '#ffffff'
      headerBackgroundColor:
        ios: '#ffffff'
        android: '#ffffff'
      headerImage: juminkeko-menu-headerImage-transparent

    mainmenu:
      type: menu
      title:
        en: Jumikeko Menu
        fi: Jumikeko valikko

      items:

        welcomeitem:
          title:
            en: About the Juminkeko
            fi: Juminkeko
          icon: 'materialcommunityicons:home'
          listeners:
            click: onWelcomeClick

        kalevalaitem:
          title:
            en: About the Kalevala
            fi: Kalevala
          icon: 'materialcommunityicons:home'
          listeners:
            click: onKalevalaClick

        buildingitem:
          title:
            en: The Building
            fi: Rakennus
          icon: 'materialcommunityicons:home'
          listeners:
            click: onBuildingClick

        activitiesitem:
          title:
            en: Activities
            fi: Tapahtumat
          icon: 'materialcommunityicons:home'
          listeners:
            click: onActivitiesClick

  mainPanel:

    activities:
      type: page
      title:
        en: Activities
        fi: Tapahtumat
      ci:
        fi: 88rt
        en: 88rt
      icon: materialcommunityicons:home
      headerNumbering: false

    building:
      type: page
      title:
        en: Building
        fi: Rakennus
      ci:
        fi: 88rt
        en: 88rt
      icon: materialcommunityicons:home
      headerNumbering: false

    welcome:
      type: page
      title:
        en: Welcome to Juminkeko
        fi: Tervetuloa Juminkekoon
      ci:
        fi: 88rt
        en: 88rt
      icon: materialcommunityicons:home
      headerNumbering: false

controllers:
  constructor:
    url: welcome
  onActivitiesClick:
    url: activities
  onBuildingClick:
    url: building
  onKalevalaClick:
    url: kalevala
  onWelcomeClick:
    url: welcome
